# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motus < Formula
  desc "A simple and elegant password generator"
  homepage "https://github.com/oleiade/motus"
  version "0.3.6"
  license "MIT"

  depends_on "rust" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oleiade/motus/releases/download/v0.3.6/motus_0.3.6_darwin_arm64.zip"
      sha256 "463450c33a5e0e1399ad1a709d621264a34a99a6274accc46b6f6c436e725418"

      def install
        bin.install "motus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oleiade/motus/releases/download/v0.3.6/motus_0.3.6_linux_amd64.tar.gz"
        sha256 "24fa7fe45452fe547d7f1da44793bb219e63c752126d60875b0aec77f9ef1b85"

        def install
          bin.install "motus"
        end
      end
    end
  end

  test do
    system "#{bin}/motus --version"
  end
end
