# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motus < Formula
  desc "A simple and elegant password generator"
  homepage "https://github.com/oleiade/motus"
  version "0.3.6"
  license "MIT"

  depends_on "rust" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oleiade/motus/releases/download/v0.3.6/motus_0.3.6_darwin_arm64.zip"
      sha256 "f2abf81494e53816d1e1f6739f6a92b8c23c0c63601b34859d85544e41e677d7"

      def install
        bin.install "motus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oleiade/motus/releases/download/v0.3.6/motus_0.3.6_linux_amd64.tar.gz"
        sha256 "3e94f3336348eb427082c7805409e3f9d6f9dfe8c7631a89a0070af66f3d7cbc"

        def install
          bin.install "motus"
        end
      end
    end
  end

  test do
    system "#{bin}/motus --version"
  end
end
