# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motus < Formula
  desc "A simple and elegant password generator"
  homepage "https://github.com/oleiade/motus"
  version "0.3.5"
  license "MIT"

  depends_on "rust" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oleiade/motus/releases/download/v0.3.5/motus_0.3.5_darwin_arm64.zip"
      sha256 "4dc39ba21bfda643e5da19c3b63c80506463ee1b07ac103ef70fa0cc116ee183"

      def install
        bin.install "motus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oleiade/motus/releases/download/v0.3.5/motus_0.3.5_linux_amd64.tar.gz"
        sha256 "313d9ca7079a6c6971d0aac7d37f81a0bc812c43a57e6a465f284af7e927e1b0"

        def install
          bin.install "motus"
        end
      end
    end
  end

  test do
    system "#{bin}/motus --version"
  end
end
