# This file was generated by GoReleaser. DO NOT EDIT.
cask "knocknock" do
  desc "A straightforward network scanner"
  homepage "https://github.com/oleiade/knocknock"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knocknock"

  on_macos do
    on_arm do
      url "https://github.com/oleiade/knocknock/releases/download/v0.1.1/knocknock_0.1.1_darwin_arm64.zip"
      sha256 "229a10c31237caf6be8ea3c8f9cf250b2609e4b7b82098f2410cc9c913b13034"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oleiade/knocknock/releases/download/v0.1.1/knocknock_0.1.1_linux_amd64.tar.gz"
      sha256 "e8836b88207d2bc36f80b047f8605855a0530727ad4de98328c2cd00aab06805"
    end
    on_arm do
      url "https://github.com/oleiade/knocknock/releases/download/v0.1.1/knocknock_0.1.1_linux_arm64.tar.gz"
      sha256 "1c4382c9b0150a2129515d6df64d075b3abc477da99da5fda70a7fdec4f7649d"
    end
  end

  # No zap stanza required
end
