# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motus < Formula
  desc "A simple and elegant password generator"
  homepage "https://github.com/oleiade/motus"
  version "0.4.0"
  license "MIT"

  depends_on "rust" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oleiade/motus/releases/download/v0.4.0/motus_0.4.0_darwin_arm64.zip"
      sha256 "e45ebff7ad470288453b6a20966a76ec82f645300977bded2249436d90f223e4"

      def install
        bin.install "motus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/motus/releases/download/v0.4.0/motus_0.4.0_linux_amd64.tar.gz"
      sha256 "6bc9087bf4f9d5ed628a29309f785f56627c2f2e9b765b8c2faa3ee1bb649141"
      def install
        bin.install "motus"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/motus/releases/download/v0.4.0/motus_0.4.0_linux_arm64.tar.gz"
      sha256 "b8975b5bf0e06842be6bfad610fb32b46005d4c77cb811d80d05934f8b8b4a94"
      def install
        bin.install "motus"
      end
    end
  end

  test do
    system "#{bin}/motus --version"
  end
end
