# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mymy < Formula
  desc "Access the most common information about your system using a single command"
  homepage "https://github.com/oleiade/mymy"
  version "0.4.0"
  license "MIT"

  depends_on "rust" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oleiade/mymy/releases/download/v0.4.0/mymy_0.4.0_darwin_arm64.zip"
      sha256 "8cfcadc366e110d088e01c46506f1da0e2a39e6bb0a68ba6435866016a88a7f0"

      def install
        bin.install "my"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/mymy/releases/download/v0.4.0/mymy_0.4.0_linux_amd64.tar.gz"
      sha256 "0d59866d6f29c023b323fa1eaa4b6638a594577270b597867db565c866ba07c1"
      def install
        bin.install "my"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/mymy/releases/download/v0.4.0/mymy_0.4.0_linux_arm64.tar.gz"
      sha256 "c8cfcd492485d4444be7cac9b58a8aeded09f01f60eb212dadcfce42c2566295"
      def install
        bin.install "my"
      end
    end
  end

  test do
    system "#{bin}/my --version"
  end
end
