# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mymy < Formula
  desc "Access the most common information about your system using a single command"
  homepage "https://github.com/oleiade/mymy"
  version "0.5.0"
  license "MIT"

  depends_on "rust" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oleiade/mymy/releases/download/v0.5.0/mymy_0.5.0_darwin_arm64.zip"
      sha256 "13c02bd41fd5585a01ce04a94d9aafbc0279628074eed7796562f2d6cb57e3d7"

      def install
        bin.install "my"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/mymy/releases/download/v0.5.0/mymy_0.5.0_linux_amd64.tar.gz"
      sha256 "a2d6c9628902f632656293c031da46b5f1c82ad576ef78846814c9d77af0e5dc"
      def install
        bin.install "my"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/mymy/releases/download/v0.5.0/mymy_0.5.0_linux_arm64.tar.gz"
      sha256 "947083f77dfbe2263f49f9302afb1433552fb1d59fbf8a24f8b2b36bf55385be"
      def install
        bin.install "my"
      end
    end
  end

  test do
    system "#{bin}/my --version"
  end
end
