# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mymy < Formula
  desc "Access the most common information about your system using a single command"
  homepage "https://github.com/oleiade/mymy"
  version "0.5.1"
  license "MIT"

  depends_on "rust" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oleiade/mymy/releases/download/v0.5.1/mymy_0.5.1_darwin_arm64.zip"
      sha256 "16c68b2c256ca9d9cc09cbdaf077b5a17d38be9b9e3ca92916090f1d4596a601"

      def install
        bin.install "my"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/mymy/releases/download/v0.5.1/mymy_0.5.1_linux_amd64.tar.gz"
      sha256 "1bba0383b436935947ee76b41d8c1043e4ec5314ede8eed8669f8c2e48c55cb6"
      def install
        bin.install "my"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oleiade/mymy/releases/download/v0.5.1/mymy_0.5.1_linux_arm64.tar.gz"
      sha256 "abdda9ed443ba4d3bc627717aac1282340210c992384f2551852ef9fb7949c66"
      def install
        bin.install "my"
      end
    end
  end

  test do
    system "#{bin}/my --version"
  end
end
