# This file was generated by GoReleaser. DO NOT EDIT.
class Trousseau < Formula
  desc "File based encrypted key-value store"
  homepage "https://github.com/oleiade/trousseau"
  version "0.4.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/oleiade/trousseau/releases/download/v0.4.1/trousseau_0.4.1_Darwin_x86_64.tar.gz"
    sha256 "8b352cd5deed46deaf2570538f3db7de21047f98a2b95fc7314f57e061afe6ad"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/oleiade/trousseau/releases/download/v0.4.1/trousseau_0.4.1_Linux_x86_64.tar.gz"
      sha256 "b6368e63702cc238fa13e53c02a725cf877d5574e3d6937076744abb97548312"
    end
  end

  def install
    bin.install "trousseau"
  end

  test do
    system "#{bin}/trousseau -v"
  end
end
